MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (1, 'JIRA_USER_TYPE', 'SEC', 'Security');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (2, 'JIRA_USER_TYPE', 'QE', 'QE');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (3, 'JIRA_USER_TYPE', 'CLDEV', 'CLDev');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (4, 'JIRA_USER_TYPE', 'CLQE', 'CLQe');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (5, 'JIRA_USER_TYPE', 'LT', 'LT');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (6, 'JIRA_USER_TYPE', 'PO', 'PO');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (7, 'JIRA_USER_TYPE', 'OPS', 'Ops');


MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (8, 'APP_CONFIG', 'REPO_DELIVERY_URL', 'repo_url');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (9, 'APP_CONFIG', 'REPO_DELIVERY_NAME', 'repo_name');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (10, 'APP_CONFIG', 'BRANCH_DELIVERY_TEMPLATE', 'branch_template');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (11, 'APP_CONFIG', 'RUTA_JSON_DELIVERY', 'ruta_json_delivery');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (12, 'APP_CONFIG', 'RUTA_JSON_JIRA', 'ruta_json_jira');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (13, 'APP_CONFIG', 'JIRA_API_URL', 'jira_api_url');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (14, 'APP_CONFIG', 'CHAMA_API_URL', 'chama_api_url');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (15, 'USER_CONFIG', 'NAME', 'name');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (16, 'USER_CONFIG', 'EMAIL', 'email');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (17, 'USER_CONFIG', 'USERNAME', 'username');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (18, 'USER_CONFIG', 'PASSWORD', 'password');

MERGE INTO CONFIG (ID, CONFIG_GROUP, CONFIG_TYPE, CONFIG_VALUE)
    VALUES (19, 'USER_CONFIG', 'COOKIE', 'cookie');


